import { IPokemon } from "../../types";

export const getAllPokemonFields = (): (keyof IPokemon)[] => [
  "name",
  "pokedexNumber",
  "imgName",
  "generation",
  "evolutionStage",
  "evolved",
  "familyId",
  "crossGen",
  "type1",
  "type2",
  "weather1",
  "weather2",
  "statTotal",
  "atk",
  "def",
  "sta",
  "legendary",
  "aquirable",
  "spawns",
  "regional",
  "raidable",
  "hatchable",
  "shiny",
  "nest",
  "new",
  "notGettable",
  "futureEvolve",
  "cp40",
  "cp39",
];
